### ISSUE TITLE
Warning: React does not recognize the `handleAxis` prop on a DOM element

### ISSUE THREAD

**Issue by evoyy** [react-grid-layout/react-resizable#175]
I started seeing this warning in the console after updating from 3.0.1 -> 3.0.2

I'm using the component as follows:

````javascript
<ResizableBox
    handle={<span className="resize-handle" />}
    ...
>

**Comment by STRML** [comment]
Fixed in 9082fec, will release soon

**Comment by evoyy** [comment]
Sorry, I'm still seeing this warning after upgrading to 3.0.3

**Comment by STRML** [comment]
Thanks. Made a mistake in the fix. Fixed in 3.0.4.

**Comment by Peatechen** [comment]
Sorry, I'm still seeing this warning after upgrading to 3.0.4

**Comment by danben4** [comment]
Any news on this? 🤓

**Comment by wiyantotan** [comment]
same here
